### ISSUE TITLE
这个工具是golang开发的?

### ISSUE THREAD

**Issue by wujunze** [xiaoqidun/whois#1]
这个工具是golang开发的?

**Comment by xiaoqidun** [comment]
是的

Panda <notifications@github.com>于2018年5月18日周五 下午1:13写道：

**Comment by wujunze** [comment]
你这个是编译后的二进制文件啊    源代码没有开源😀

**Comment by xiaoqidun** [comment]
这个程序只是https://whois.aite.xyz/的客户端而已，本身也是请求whois.aite.xyz的api进行查询的，
whois.aite.xyz提供了查询api。

Panda <notifications@github.com>于2018年5月18日周五 下午5:02写道：

**Comment by wujunze** [comment]
嗯  那就是用goLang包装http请求

**Comment by xiaoqidun** [comment]
https://whois.aite.xyz/?ajax&client&domain=aite.xyz
这个就是api，你可以自己调用，client参数代表直接换行 客户端使用，不带client参数就是ajax方式调用，使用<br>换行（网页专用）。

Panda <notifications@github.com>于2018年5月18日周五 下午5:09写道：

**Comment by xiaoqidun** [comment]
所有查询的实现是php写的，只是用golang简单包装了个客户端，方便命令行使用。

肖其顿 <xiaoqidun@gmail.com>于2018年5月18日周五 下午5:08写道：

**Comment by wujunze** [comment]
OK Thanks
